---
- hosts: tomcat
  tasks:
   - name: checking ping connectivity
     ping:

   - name: copy file from jenkins to tomcat server
     copy:
      src: /var/lib/jenkins/workspace/ci-cd/target/sindhu-demo.war
      dest: /opt/tomcat/webapps

   - name: stop tomcat service
     shell: service tomcat stop

   - name: start tomcat service
     shell: service tomcat start
