---
- hosts: localhost
  tasks: 
   - name: ping
     ping:

   - name: update IP txt file with inputs
     lineinfile:
       dest: /tmp/IP.txt
       line: "{{ item }}"
       insertafter: EOF
    
     with_items:
         - 192.168.0.0 255.255.255.255
         - 192.168.1.1 255.255.255.256

   - name: Git checkout
     ansible.builtin.git:
        repo: https://pasupureddy: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@github.com/pasupureddy/koti-devops.git
        dest: /tmp/1
        version: main
        update: yes

   - name: copy updated IP.txt file to git repo
     fetch:
       src: /tmp/IP.txt
       dest: /tmp/1
     ignore_errors: yes
   - name: git status
     shell: "{{ item }}"
     
     with_items:
       - git status
       - git add .
       - git commit -m "update"
       - git push


   - name: git add 
     shell: git add . 
     args:
      chdir: /tmp/1

   - name: git commit 
     shell: git commit -m "test from ansible"
     args:
       chdir: /tmp/1

   - name: git push
     shell: git push
     args: 
       chdir: /tmp/1
 
